version: "3.8"

services:
  app:
    build: .
    image: node-app-image-1
    ports:
      - "4002:4001"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      MONGO_URI: mongodb://user:user123@mongo:27017/
      APP_PORT: 4001
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user123
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: user123
      ME_CONFIG_MONGODB_URL: mongodb://user:user123@mongo:27017/
      ME_CONFIG_BASICAUTH: "false"

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins-docker
    ports:
      - "8080:8080"
    privileged: true
    volumes:
      - type: bind
        source: "//./pipe/docker_engine"
        target: "//./pipe/docker_engine"
      - type: bind
        source: "C:/Users/HP/.docker"
        target: "/root/.docker"
      - jenkins_home:/var/jenkins_home
    environment:
      - DOCKER_HOST=npipe:////./pipe/docker_engine

  ssh-agent:
    image: jenkins/ssh-agent

volumes:
  mongo_data:
  jenkins_home:
