version: "3.8"

services:
  app:
    build: .
    image: node-app-image-1
    ports:
      - "4002:4001"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      MONGO_URI: mongodb://user:user123@mongo:27017/
      APP_PORT: 4001
    depends_on:
      - mongo
