version: "3.8"

services:
  app:
    image: node-app-image-1 
    build: .
    ports:
      - "4000:4000" 
    volumes:
      - ./:/app 
      - /app/node_modules
    environment:
      MONGO_URI: "mongodb+srv://user:user123@cluster0.kcokk.mongodb.net/"
      PORT: "4000"
