version: "3.8"

services:
  app:
    build: .
    image: node-app-image-1
    ports:
      - "4002:4001"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      MONGO_URI: mongodb://user:user123@mongo:27017/
      APP_PORT: 4001
      JWT_SECRET: 3f@9!kL2$zX8^pQwR&7*YtN0oV!mJd
      KAFKA_BROKER: broker:9092
      MYSQL_URL: mysql://user:user123@db:3306/db
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
      MYSQL_ROOT_PASSWORD: root123
    networks:
      - shared-network  # Use the shared network

networks:
  shared-network:
    external: true  # Ensure the network is defined externally
