apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  type: NodePort
  selector:
    app: notification
  ports:
    - port: 4002 # Kubernetes service port -port service exposes inside cluster & on your local machine
      targetPort: 4001 # Port in container (should match containerPort)
      nodePort: 30080 # Exposed port on Node/Minikube

# to expose the Pods to be accessible inside/outside the cluster
