apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  MONGO_URI: bW9uZ29kYjovL3VzZXI6dXNlcjEyM0Btb25nby1zZXJ2aWNlOjI3MDE3Lw==
  JWT_SECRET: M2ZAKDlrbDIkekg4XlBRd1ImNypZdE4wb1YhbUpk
  MYSQL_URL: bXlzcWw6Ly91c2VyOnVzZXIxMjNAbXlzcWwtc2VydmljZTozMzA2L2Ri
  MYSQL_DATABASE: ZGI=
  MYSQL_HOST: bXlzcWwtc2VydmljZQ==
  MYSQL_USER: dXNlcg==
  MYSQL_PASSWORD: dXNlcjEyMw==
  MYSQL_ROOT_PASSWORD: cm9vdDEyMw==
