apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
    - protocol: TCP
      port: 29092
      targetPort: 29092
    - protocol: TCP
      port: 9093
      targetPort: 9093
