version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user123'
      MYSQL_ROOT_PASSWORD: 'root123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - shared-network  # Connect Jenkins to the shared network

  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: mysql-workbench
    cap_add:
      - IPC_LOCK
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /c/Users/HP/mysql-workbench-config/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped
    networks:
      - shared-network  # Connect Jenkins to the shared network

volumes:
  my-db:

networks:
  shared-network:
    external: true  # Use the shared external network