name: Node.js CI/CD
on: [push]

jobs:
  build-only:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      
      # Install dependencies
      - run: npm install
      
      # (Optional) Start the server - for manual validation/debug
      - run: node index.js
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        continue-on-error: true  # Prevents workflow failure if server runs indefinitely
