name: Node.js CI/CD with MongoDB
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:latest  # Use the official MongoDB Docker image
        env:
          MONGO_INITDB_ROOT_USERNAME: user
          MONGO_INITDB_ROOT_PASSWORD: user123
        ports:
          - 27017:27017  # Expose MongoDB port

    steps:
      # Checkout code
      - uses: actions/checkout@v4
      
      # Set up Node.js environment
      - uses: actions/setup-node@v4
        with:
          node-version: 16

      # Install dependencies
      - run: npm install

      # Build and run the app (connects to MongoDB via Docker)
      - run: |
          echo "Connecting to MongoDB at mongodb://user:user123@localhost:27017/"
          npm start  # Or your start script for the app, ensure this runs the app
        env:
          MONGO_URI: mongodb://user:user123@localhost:27017/
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: 4001  # Port your app is using
